### PR TITLE
Update for 1.4

### PR DESCRIPTION
**Pull request by pyrex41**
Updated types syntax, and rewrote tests using Tests instead of FactCheck.

### CODE REVIEW

**Comment by tshort** [comment]
Nice job, @pyrex41! 

It doesn't look like tests are running as part of this PR. Maybe `.travis.yml` needs to be updated. Any other ideas?

**Comment by tshort** [comment]
I'm not sure why it's not showing on the PR, but it's failing on Travis:

https://travis-ci.org/github/tshort/ReactiveBasics.jl/jobs/675499820

I think that `Test` needs to be added to `Project.toml`, or there needs to be another `Project.toml` in the `test` directory.

**Comment by pyrex41** [comment]
I’m reading the Travis docs now...have not used it before, I definitely
hadn’t configured it correctly. When I tested before submitting I just ran
the test file manually from the command line.

**Comment by pyrex41** [comment]
Looks like i just had to change the Julia Versions in trav yaml file, and also to add the Test package using the julia pkg manager. Looks to me like it is working now.

**Comment by tshort** [comment]
Adding `Test` that way works, but it's not best practice. I should have been more specific. It's better to add `Test` in `extras` like [this](https://github.com/JuliaData/DataFrames.jl/blob/eb6fc526957cd17d78ffdf80e59aff1cb7102569/Project.toml#L29-L32). 

[Here](https://discourse.julialang.org/t/using-test-project-toml/31406)'s another way to do it.

**Comment by pyrex41** [comment]
Fixed. Really odd how you have to manually edit the Project.toml to make that work...looks like issues have been open on this for a few years now too but probably not really high on the priority list.

**Comment by tshort** [comment]
Looks good to me...

**Comment by tshort** [comment]
You don't happen to know the latest process for tagging and publishing a package, do you @pyrex41?

**Comment by pyrex41** [comment]
I have not actually done this, but I think that [this](https://github.com/JuliaRegistries/Registrator.jl) is currently the process. Docs [here](https://juliaregistries.github.io/Registrator.jl/stable/webui/#Usage-(For-Package-Maintainers)-1).

**Comment by pyrex41** [comment]
You may need to update the Project.toml; it has my username in it.

**Pull request merged**
